app:
  mode: "release"
  logLevel: "error"

mysql:
  host: localhost
  port: 3307
  username: "root"
  password: "123456"
  database: "go_ticket"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"
  maxOpenConns: 200
  maxIdleConns: 50
  connMaxLifetime: 3600

redis:
  addr: "localhost:6379"
  password: "123456"
  db: 0
  poolSize: 200
  minIdleConns: 50
  dialTimeout: 5